# Generated by Django 5.2 on 2025-04-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_date_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='keywords',
        ),
    ]
