# Generated by Django 5.1.7 on 2025-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_task_options_remove_task_course_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(default=0, upload_to='tasks/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='CourseFile',
        ),
    ]
